### ISSUE TITLE
Doesn't build with base64-bytestring 1.1.0.0

### ISSUE THREAD

**Issue by felixonmars** [fpco/haskell-ide#4]
```
[1 of 1] Compiling Text.ProjectTemplate ( Text/ProjectTemplate.hs, dist/build/Text/ProjectTemplate.dyn_o )

Text/ProjectTemplate.hs:60:21: error:
    Not in scope: ‘B64.joinWith’
    Module ‘Data.ByteString.Base64’ does not export ‘joinWith’.
   |
60 |             yield $ B64.joinWith "\n" 76 $ B64.encode bs
   |                     ^^^^^^^^^^^^
```

They have removed `joinWith` in haskell/base64-bytestring#32

**Comment by aquiandres** [comment]
I had to run the following command in order to successfully install yesod-bin:

```
$ cabal install yesod-bin --constraint=base64-bytestring==1.0.0.3
```

Version 1.0.0.3 was the last one with `joinWith`.  Hopefully this will be addressed in the near future.

**Comment by snoyberg** [comment]
Sorry, didn't notice this at first, releasing new version now.
